services:
  - type: web
    name: student-management-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn school_app.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.2
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
